language: node_js
cache: yarn
node_js:
  - "7"

script: yarn run test && yarn run generate-coverage

before_install:
  - pip install --user codecov
after_success:
  - codecov --file coverage/lcov.info --disable search
